import './globals.css'

export const metadata = {
  title: 'Web tutorilas',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html>      
      <body>        
      <header className="text-gray-600 body-font">
        <div className="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
          <a className="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0">            
            <span className="ml-3 text-xl">MDB</span>
          </a>
          <nav className="md:ml-auto flex flex-wrap items-center text-base justify-center">
            <a className="mr-5 hover:text-gray-900">Home</a>
            <a className="mr-5 hover:text-gray-900">About</a>
            <a className="mr-5 hover:text-gray-900">Search</a>
          </nav>          
        </div>
        </header>
        <div className="container mx-auto">
        <ol>
          <li><a href="/read/1">html</a></li>
          <li><a href="/read/2">css</a></li>
        </ol>
        {children}
        <ul>
          <li><a href="/create">create</a></li>
          <li><a href="/update/1">update</a></li>
          <li><input type="button" value="delete"/></li>
        </ul>  
        </div>        
      </body>
    </html>
  )
}
